on:
  push:
    branches: [ main ]
name: Deploy website on push
jobs:
  web-deployed:
    name: Auto Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: action@checkout v2.3.2

  - name: Rsync Deployments Action
  # You may pin to the exact commit or the version.
  # uses: Burnett01/rsync-deployments@796cf0d5e4b535745ce49d7429f77cf39e25ef39
  uses: Burnett01/rsync-deployments@7.0.1
  with:
    # The switches
    switches: -avzr --delete
    # The remote shell argument
    rsh: # optional, default is 
    # Enables support for legacy RSA host keys on OpenSSH 8.8+
    legacy_allow_rsa_hostkeys: # optional, default is false
    # The local path
    path: # optional, default is 
    # The remote path
    remote_path: /var/www/tesh_ssh
    # The remote host
    remote_host: 35.247.130.67/
    # The remote user
    remote_user: notyouriiz
    # The remote key
    remote_key: ${{ secrets.DEPLOY_KEY_SSH }}
