on:
  push:
    branches: [ main ]
name: Deploy website on push
jobs:
  web-deploy:
    name: Auto Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Rsync Deployments Action
      uses: Burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzr --delete
        path: /
        remote_path: /var/www/tesh_ssh
        remote_host: 35.247.130.67
        remote_user: lenovo
        remote_key: ${{ secrets.PRIVATE_SSH_KEY }}
